### ISSUE TITLE
Display the functions & its names differently in the UI 

### ISSUE THREAD

**Issue by philipleindecker** [tiqi-group/pydase#90]
The functions are being displayed weirdly and its not possible to just fix this with css

**Comment by evecui250** [comment]
the function's default parameters are not shown on the UI

**Comment by mosmuell** [comment]
Functions that are rendered in the frontend will not be allowed to have arguments in the next release. You can only expose synchronous functions that have no arguments and are decorated with the "@frontend" decorator.
Instead of arguments, you can access attributes of the service class in the function body.
